// src/components/FormInputs/General/index.jsx
import React from 'react';
import { useGenerator } from '../../../state/GeneratorContext';
import Card from '../card';
import FormTextInput from '../../Common/FormTextInput';

const General = () => {
    const { general, updateGeneral } = useGenerator();

    return (
        <Card sectionName="General Information">
            <div className="row">
                <FormTextInput
                    label="Plugin Name"
                    value={general.pluginName}
                    onChange={(v) => updateGeneral('pluginName', v)}
                    placeholder="My Awesome Plugin"
                />
                <FormTextInput
                    label="Plugin URI"
                    value={general.pluginURI}
                    onChange={(v) => updateGeneral('pluginURI', v)}
                    placeholder="https://example.com"
                />
                <FormTextInput
                    label="Description"
                    value={general.description}
                    onChange={(v) => updateGeneral('description', v)}
                    placeholder="Brief description of your plugin"
                    col={12}
                />
                <FormTextInput label="Version" value={general.version} onChange={(v) => updateGeneral('version', v)} col={4} />
                <FormTextInput label="Author" value={general.author} onChange={(v) => updateGeneral('author', v)} col={4} />
                <FormTextInput label="Author Email" value={general.authorEmail} onChange={(v) => updateGeneral('authorEmail', v)} col={4} />
                <FormTextInput label="Text Domain" value={general.textDomain} onChange={(v) => updateGeneral('textDomain', v)} col={6} />
                <FormTextInput label="Domain Path" value={general.domainPath} onChange={(v) => updateGeneral('domainPath', v)} col={6} />
            </div>
        </Card>
    );
};

export default General;

// src/components/FormInputs/General/index.vue
<template>
  <div>
    <card sectionName="General">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="name">Plugin Name</label>
            <input
              type="text"
              name="name"
              class="form-control"
              autocomplete="off"
              v-model="pluginName"
            />
          </div>
        </div>

        <text-input label="Plugin URI" objkey="pluginURI" />
        <text-input label="Description" objkey="description" :col="12" />
        <text-input label="Version" objkey="version" />
        <text-input label="Author" objkey="author" />
        <text-input label="Author URI" objkey="authorURI" />
        <text-input label="Author Email" objkey="authorEmail" />
        <text-input label="License" objkey="license" />
        <text-input label="License URI" objkey="licenseURI" />
        <text-input
          label="Text Domain"
          objkey="textDomain"
          convert-case="slug"
        />
        <text-input label="Domain Path" objkey="domainPath" />
      </div>
    </card>
  </div>
</template>

<script>
import textInput from "../textInput.vue";
import card from "../card.vue";

export default {
  name: "General",
  computed: {
    pluginName: {
      get() {
        return this.$store.getters.pluginName;
      },
      set(val) {
        this.$store.dispatch("setPluginName", val);
      },
    },
  },
  components: {
    textInput,
    card,
  },
};
</script>

<style lang="scss" scoped></style>
