// src/components/Common/FormTextInput.vue
<template>
  <div class="form-group mb-3">
    <label v-if="label">{{ label }}</label>
    <span class="form-text d-block mb-1" v-if="helptext !== ''">{{ helptext }}</span>
    <input
      type="text"
      class="form-control"
      :placeholder="placeholder"
      :value="modelValue"
      @input="$emit('update:modelValue', $event.target.value)"
      :disabled="disabled"
      autocomplete="off"
    />
  </div>
</template>

<script>
export default {
  props: {
    label: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    modelValue: { type: [String, Number], default: "" },
    disabled: { type: Boolean, default: false },
    helptext: { type: String, default: "" },
  },
  emits: ['update:modelValue']
};
</script>

// src/components/Common/FormTextInput.jsx
import React from 'react';

const FormTextInput = ({ label, value, onChange, placeholder, helptext, disabled, col = 12 }) => {
    return (
        <div className={`col-md-${col} mb-3`}>
            <div className="form-group">
                {label && <label className="form-label">{label}</label>}
                {helptext && <span className="form-text d-block mb-1">{helptext}</span>}
                <input
                    type="text"
                    className="form-control"
                    placeholder={placeholder}
                    value={value || ''}
                    onChange={(e) => onChange(e.target.value)}
                    disabled={disabled}
                    autoComplete="off"
                />
            </div>
        </div>
    );
};

export default FormTextInput;
