// src/components/FormInputs/Advanced/index.vue
<template>
  <div>
    <card sectionName="Advanced">
      <div class="row">
        <text-input
          label="Base Namespace"
          objkey="baseNamespace"
          convert-case="title"
          helptext="Plugin initial namespace. ex: WPGenerator\Weather"
          placeholder="WPGenerator\Weather"
        />

        <text-input
          label="Main Class Name"
          objkey="mainClassName"
          convert-case="title"
          helptext="Main class name of the plugin. ex: Weather"
          placeholder="Weather"
        />

        <text-input
          label="Constant Prefix"
          objkey="constantPrefix"
          convert-case="slug"
          separator="_"
          helptext="Plugin constant prefix. ex: WF_WEATHER"
          placeholder="WF_WEATHER"
        />

        <text-input
          label="Function Prefix"
          objkey="functionPrefix"
          convert-case="slug"
          separator="_"
          helptext="Plugin function prefix. ex: wf_get_weather"
          placeholder="wf_get_weather"
        />
      </div>
    </card>
  </div>
</template>

<script>
import textInput from "../textInput.vue";
import card from "../card.vue";
export default {
  components: {
    textInput,
    card,
  },
};
</script>

<style lang="scss" scoped></style>

// src/components/FormInputs/Advanced/index.jsx
import React from 'react';
import { useGenerator } from '../../../state/GeneratorContext';
import Card from '../card';
import FormTextInput from '../../Common/FormTextInput';
import { titleCase } from '../../../utils/helpers';

const Advanced = () => {
    const { general, updateGeneral, slug } = useGenerator();

    return (
        <Card sectionName="Advanced Configuration">
            <div className="row">
                <FormTextInput
                    label="Base Namespace"
                    value={general.baseNamespace}
                    onChange={(v) => updateGeneral('baseNamespace', titleCase(v).replace(/\s/g, '_'))}
                    helptext="e.g., MyPlugin\Core"
                />
                <FormTextInput
                    label="Main Class Name"
                    value={general.mainClassName}
                    onChange={(v) => updateGeneral('mainClassName', titleCase(v).replace(/\s/g, ''))}
                />
                <FormTextInput
                    label="Constant Prefix"
                    value={general.constantPrefix}
                    onChange={(v) => updateGeneral('constantPrefix', slug(v, '_').toUpperCase())}
                />
                <FormTextInput
                    label="Function Prefix"
                    value={general.functionPrefix}
                    onChange={(v) => updateGeneral('functionPrefix', slug(v, '_'))}
                />
            </div>
        </Card>
    );
};

export default Advanced;
